### ISSUE TITLE
fatal: could not read from remote repository

### ISSUE THREAD

**Issue by geofflangenderfer** [aforemny/bullet-journal#1]
I performed the following commands successfully:
```bash
git clone git@github.com:aforemny/bullet-journal.git
cd bullet-journal

```
Then got the following error. Any advice?:
```bash
git submodule update --init                        

Cloning into '/home/geoff/work/bullet-journal/src/material-components-elm'...
geoff@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'github.com:aforemny/material-components-elm.git' into submodule path '/home/geoff/work/bullet-journal/src/material-components-elm' failed
Failed to clone 'src/material-components-elm'. Retry scheduled
Cloning into '/home/geoff/work/bullet-journal/src/material-components-elm'...
geoff@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'github.com:aforemny/material-components-elm.git' into submodule path '/home/geoff/work/bullet-journal/src/material-components-elm' failed
Failed to clone 'src/material-components-elm' a second time, aborting
```

**Comment by aforemny** [comment]
Hi @geofflangenderfer, thank you for reporting this. I have fixed the issue with the latest commit in master. If you have to fiddle with submodules, it might be easiest to clone this repository again and start over.

What were you expecting to find here? Unfortunately, this project lost traction as of currently, and just about everything is very much unfinished.

**Comment by geofflangenderfer** [comment]
I like the bullet journal and hate GUIs, so I was surveying the cli bullet journal landscape. I'll give it another shot, thanks for your effort and well done with this project!

**Comment by aforemny** [comment]
@geofflangenderfer I see. Thanks! :) Unfortunately, this is not a CLI project. Good luck with the search!
